### ISSUE TITLE
Ability to scan walletUrl to list/show all historical blocks won

### ISSUE THREAD

**Issue by PsyDafke** [felixbrucker/bhd-burst-proxy#132]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just an enhancement

**Describe the solution you'd like**
possibility to let it scan the walletUrl for historical blocks won... maybe a startupflag, so it doesn't always runs each launch.

**Describe alternatives you've considered**

**Additional context**

**Comment by felixbrucker** [comment]
Closed with https://github.com/felixbrucker/bhd-burst-proxy/commit/a8e3ea60bec8b2829b46cce1dcab2310f327b89a
