### ISSUE TITLE
mail notifications for offline miners

### ISSUE THREAD

**Issue by pokermaster100** [felixbrucker/bhd-burst-proxy#240]
**Describe the solution you'd like**
The status indicators for the miners in the Webui are helpful, but it would be nice to get emails and/or SMS messages if a miner is offline or has not submitted dealdines recently.

**Describe alternatives you've considered**
Swatchdog to monitor logs files.

**Comment by felixbrucker** [comment]
Closed with https://github.com/felixbrucker/bhd-burst-proxy/commit/6400c9e1624b6cd8bb09cdf2d67b331689adb62c
