### ISSUE TITLE
Display Proxy Version in GUI

### ISSUE THREAD

**Issue by locknum** [felixbrucker/bhd-burst-proxy#247]
**Is your feature request related to a problem? Please describe.**
With frequent updates to the proxy it would be beneficial to show in the GUI the current version being run, the new version (if any available) available, and perhaps a change log displaying what changes are available and if its worth upgrading.

**Describe the solution you'd like**
Place this information in the footer or in the more vertical options / hamburger menu.

**Describe alternatives you've considered**
Modify current notification of "New Version" to include "Current Version"

**Additional context**

**Comment by felixbrucker** [comment]
Closed with https://github.com/felixbrucker/bhd-burst-proxy/commit/94285e7ac0ff04ac57eca3dfb0d54ed2490ff82c
