### ISSUE TITLE
plotter ID with hyperlink to bhd/burst explore for each miner system

### ISSUE THREAD

**Issue by cybermancerr** [felixbrucker/bhd-burst-proxy#266]
**Is your feature request related to a problem? Please describe.**

It is very frustrating not being able to see plotter id for each miner pointed at the proxy and not being able to see the total capacity for the group of miners with the same plotter id.

**Describe the solution you'd like**

Adding a BURST/BHD plotter ID with relevant hyperlink to explorer in front of each miner and sorting the list by groups of the same plotter ID with total capacity right below each group of same id miners would solve this.  Then total capacity of all grouped miners at the bottom of the entire list would be reflected.

**Describe alternatives you've considered**

Currently using a spreadsheet to keep track of capacities and miners ids and have to update manually.  not a good alternative.

**Additional context**
![feature]

![list](https://user-images.githubusercontent.com/7419663/58313236-c4213880-7da8-11e9-9e70-f81458faf96a.PNG)

![feature](https://user-images.githubusercontent.com/7419663/58313341-0c405b00-7da9-11e9-9768-b0b8301ffd98.PNG)

**Comment by cybermancerr** [comment]
![feature](https://user-images.githubusercontent.com/7419663/58313305-f6cb3100-7da8-11e9-8ab5-2d28da1135d3.PNG)

**Comment by felixbrucker** [comment]
This looks more like a feature needed for pool mining to keep track of users shares/capacities, rather than the task of a proxy.

**Comment by cybermancerr** [comment]
Mainly to keeping track of each miner capacity to see if some of the drives are not working on each miner.  Would be very painful to sort through IP address currently.  Grouping the miners in logical manner would help all solo miners in this manner.  The pool part would not be complete without proper software to calculate capacity for each miner based on DLs submitted instead of paths that could be not functioning properly.  Yes it would be possible to use the proxy by a small amount of friends, but for massive pool production, real pool mining software would be required that can handle automated payouts and deadline based capacity calculations.   Felix, I would really love to see this implemented if you could, unless this somehow conflicts with things others want from the proxy.  I don't mind donating as well to see this happen :)

**Comment by felixbrucker** [comment]
As one can only get the total capacity regardless of accountId per miner, grouping/aggregating capacity per accountId is technically not possible. One can however logically group miners by using a multi proxy setup where many small miners are submitting DLs to a proxy which then reports their aggregated size to the next proxy where miners appear aggregated.

Closing here for now.
